name: DEPLOY
on:
  push:
    branches:
    - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: build/
        remote_path: /var/www/html/
        remote_host: ${{ secrets.RDC_IP }}
        remote_user: ${{ secrets.RDC_SSH_USER }}
        remote_key: ${{ secrets.RDC_SSH_PRIVATE_KEY }}
